//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tax_AK.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankData()
        {
            this.PaymentHistory = new HashSet<PaymentHistory>();
        }

        public int taskid { get; set; }
        public int ItbId { get; set; }
        public string BankName { get; set; }
        public string HeadOfficeAddress { get; set; }
        public string ContactPhonenumber { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedAuthid { get; set; }
        public string LastModifiedUid { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentHistory> PaymentHistory { get; set; }
    }
}
