//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tax_AK.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class New_TaxProEntities : DbContext
    {
        public New_TaxProEntities()
            : base("name=New_TaxProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankData> BankData { get; set; }
        public virtual DbSet<CompanyData> CompanyData { get; set; }
        public virtual DbSet<PayeAgent> PayeAgent { get; set; }
        public virtual DbSet<PaymentHistory> PaymentHistory { get; set; }
        public virtual DbSet<PersonalData> PersonalData { get; set; }
        public virtual DbSet<TaxReturn> TaxReturn { get; set; }
        public virtual DbSet<TaxType> TaxType { get; set; }
        public virtual DbSet<TINverification> TINverification { get; set; }
        public virtual DbSet<TransactionDetail> TransactionDetail { get; set; }
    
        public virtual ObjectResult<GET_BankData_Result> GET_BankData(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_BankData_Result>("GET_BankData", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_CompanyData_Result> GET_CompanyData(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_CompanyData_Result>("GET_CompanyData", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_PayeAgent_Result> GET_PayeAgent(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_PayeAgent_Result>("GET_PayeAgent", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_PaymentHistory_Result> GET_PaymentHistory(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_PaymentHistory_Result>("GET_PaymentHistory", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_PersonalData_Result> GET_PersonalData(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_PersonalData_Result>("GET_PersonalData", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_TaxReturn_Result> GET_TaxReturn(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_TaxReturn_Result>("GET_TaxReturn", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_TaxType_Result> GET_TaxType(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_TaxType_Result>("GET_TaxType", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_TINverification_Result> GET_TINverification(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_TINverification_Result>("GET_TINverification", itbidParameter, taskidParameter);
        }
    
        public virtual ObjectResult<GET_TransactionDetail_Result> GET_TransactionDetail(Nullable<long> itbid, Nullable<int> taskid)
        {
            var itbidParameter = itbid.HasValue ?
                new ObjectParameter("itbid", itbid) :
                new ObjectParameter("itbid", typeof(long));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_TransactionDetail_Result>("GET_TransactionDetail", itbidParameter, taskidParameter);
        }
    
        public virtual int POST_BankData(Nullable<int> itbId, string bankName, string headOfficeAddress, string contactPhonenumber, string contactEmail, Nullable<System.DateTime> lastModifiedDate, string lastModifiedAuthid, string lastModifiedUid, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var bankNameParameter = bankName != null ?
                new ObjectParameter("BankName", bankName) :
                new ObjectParameter("BankName", typeof(string));
    
            var headOfficeAddressParameter = headOfficeAddress != null ?
                new ObjectParameter("HeadOfficeAddress", headOfficeAddress) :
                new ObjectParameter("HeadOfficeAddress", typeof(string));
    
            var contactPhonenumberParameter = contactPhonenumber != null ?
                new ObjectParameter("ContactPhonenumber", contactPhonenumber) :
                new ObjectParameter("ContactPhonenumber", typeof(string));
    
            var contactEmailParameter = contactEmail != null ?
                new ObjectParameter("ContactEmail", contactEmail) :
                new ObjectParameter("ContactEmail", typeof(string));
    
            var lastModifiedDateParameter = lastModifiedDate.HasValue ?
                new ObjectParameter("LastModifiedDate", lastModifiedDate) :
                new ObjectParameter("LastModifiedDate", typeof(System.DateTime));
    
            var lastModifiedAuthidParameter = lastModifiedAuthid != null ?
                new ObjectParameter("LastModifiedAuthid", lastModifiedAuthid) :
                new ObjectParameter("LastModifiedAuthid", typeof(string));
    
            var lastModifiedUidParameter = lastModifiedUid != null ?
                new ObjectParameter("LastModifiedUid", lastModifiedUid) :
                new ObjectParameter("LastModifiedUid", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_BankData", itbIdParameter, bankNameParameter, headOfficeAddressParameter, contactPhonenumberParameter, contactEmailParameter, lastModifiedDateParameter, lastModifiedAuthidParameter, lastModifiedUidParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_CompanyData(Nullable<int> itbId, string taxID, string companyName, string companyTIN, string tINVerificationstatus, Nullable<int> companyTaxtype, string companyAddress, string companyPhonenumber, string companyAltNumber, string companyEmail, string companyAltEmail, string companyRegNo, Nullable<System.DateTime> companyStartDate, Nullable<System.DateTime> lastModifiedDate, string lastModifiedAuthid, string lastModifiedUid, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var taxIDParameter = taxID != null ?
                new ObjectParameter("TaxID", taxID) :
                new ObjectParameter("TaxID", typeof(string));
    
            var companyNameParameter = companyName != null ?
                new ObjectParameter("CompanyName", companyName) :
                new ObjectParameter("CompanyName", typeof(string));
    
            var companyTINParameter = companyTIN != null ?
                new ObjectParameter("CompanyTIN", companyTIN) :
                new ObjectParameter("CompanyTIN", typeof(string));
    
            var tINVerificationstatusParameter = tINVerificationstatus != null ?
                new ObjectParameter("TINVerificationstatus", tINVerificationstatus) :
                new ObjectParameter("TINVerificationstatus", typeof(string));
    
            var companyTaxtypeParameter = companyTaxtype.HasValue ?
                new ObjectParameter("CompanyTaxtype", companyTaxtype) :
                new ObjectParameter("CompanyTaxtype", typeof(int));
    
            var companyAddressParameter = companyAddress != null ?
                new ObjectParameter("CompanyAddress", companyAddress) :
                new ObjectParameter("CompanyAddress", typeof(string));
    
            var companyPhonenumberParameter = companyPhonenumber != null ?
                new ObjectParameter("CompanyPhonenumber", companyPhonenumber) :
                new ObjectParameter("CompanyPhonenumber", typeof(string));
    
            var companyAltNumberParameter = companyAltNumber != null ?
                new ObjectParameter("CompanyAltNumber", companyAltNumber) :
                new ObjectParameter("CompanyAltNumber", typeof(string));
    
            var companyEmailParameter = companyEmail != null ?
                new ObjectParameter("CompanyEmail", companyEmail) :
                new ObjectParameter("CompanyEmail", typeof(string));
    
            var companyAltEmailParameter = companyAltEmail != null ?
                new ObjectParameter("CompanyAltEmail", companyAltEmail) :
                new ObjectParameter("CompanyAltEmail", typeof(string));
    
            var companyRegNoParameter = companyRegNo != null ?
                new ObjectParameter("CompanyRegNo", companyRegNo) :
                new ObjectParameter("CompanyRegNo", typeof(string));
    
            var companyStartDateParameter = companyStartDate.HasValue ?
                new ObjectParameter("CompanyStartDate", companyStartDate) :
                new ObjectParameter("CompanyStartDate", typeof(System.DateTime));
    
            var lastModifiedDateParameter = lastModifiedDate.HasValue ?
                new ObjectParameter("LastModifiedDate", lastModifiedDate) :
                new ObjectParameter("LastModifiedDate", typeof(System.DateTime));
    
            var lastModifiedAuthidParameter = lastModifiedAuthid != null ?
                new ObjectParameter("LastModifiedAuthid", lastModifiedAuthid) :
                new ObjectParameter("LastModifiedAuthid", typeof(string));
    
            var lastModifiedUidParameter = lastModifiedUid != null ?
                new ObjectParameter("LastModifiedUid", lastModifiedUid) :
                new ObjectParameter("LastModifiedUid", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_CompanyData", itbIdParameter, taxIDParameter, companyNameParameter, companyTINParameter, tINVerificationstatusParameter, companyTaxtypeParameter, companyAddressParameter, companyPhonenumberParameter, companyAltNumberParameter, companyEmailParameter, companyAltEmailParameter, companyRegNoParameter, companyStartDateParameter, lastModifiedDateParameter, lastModifiedAuthidParameter, lastModifiedUidParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_PayeAgent(Nullable<int> itbId, string taxID, string agentID, string agentFirstname, string agentMidname, string agentLastname, string agentAddress, string agentPhonenumber, string agentEmail, string agentPosition, Nullable<int> companyID, Nullable<System.DateTime> lastModifiedDate, string lastModifiedAuthid, string lastModifiedUid, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var taxIDParameter = taxID != null ?
                new ObjectParameter("TaxID", taxID) :
                new ObjectParameter("TaxID", typeof(string));
    
            var agentIDParameter = agentID != null ?
                new ObjectParameter("AgentID", agentID) :
                new ObjectParameter("AgentID", typeof(string));
    
            var agentFirstnameParameter = agentFirstname != null ?
                new ObjectParameter("AgentFirstname", agentFirstname) :
                new ObjectParameter("AgentFirstname", typeof(string));
    
            var agentMidnameParameter = agentMidname != null ?
                new ObjectParameter("AgentMidname", agentMidname) :
                new ObjectParameter("AgentMidname", typeof(string));
    
            var agentLastnameParameter = agentLastname != null ?
                new ObjectParameter("AgentLastname", agentLastname) :
                new ObjectParameter("AgentLastname", typeof(string));
    
            var agentAddressParameter = agentAddress != null ?
                new ObjectParameter("AgentAddress", agentAddress) :
                new ObjectParameter("AgentAddress", typeof(string));
    
            var agentPhonenumberParameter = agentPhonenumber != null ?
                new ObjectParameter("AgentPhonenumber", agentPhonenumber) :
                new ObjectParameter("AgentPhonenumber", typeof(string));
    
            var agentEmailParameter = agentEmail != null ?
                new ObjectParameter("AgentEmail", agentEmail) :
                new ObjectParameter("AgentEmail", typeof(string));
    
            var agentPositionParameter = agentPosition != null ?
                new ObjectParameter("AgentPosition", agentPosition) :
                new ObjectParameter("AgentPosition", typeof(string));
    
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var lastModifiedDateParameter = lastModifiedDate.HasValue ?
                new ObjectParameter("LastModifiedDate", lastModifiedDate) :
                new ObjectParameter("LastModifiedDate", typeof(System.DateTime));
    
            var lastModifiedAuthidParameter = lastModifiedAuthid != null ?
                new ObjectParameter("LastModifiedAuthid", lastModifiedAuthid) :
                new ObjectParameter("LastModifiedAuthid", typeof(string));
    
            var lastModifiedUidParameter = lastModifiedUid != null ?
                new ObjectParameter("LastModifiedUid", lastModifiedUid) :
                new ObjectParameter("LastModifiedUid", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_PayeAgent", itbIdParameter, taxIDParameter, agentIDParameter, agentFirstnameParameter, agentMidnameParameter, agentLastnameParameter, agentAddressParameter, agentPhonenumberParameter, agentEmailParameter, agentPositionParameter, companyIDParameter, lastModifiedDateParameter, lastModifiedAuthidParameter, lastModifiedUidParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_PaymentHistory(Nullable<int> itbID, string taxID, Nullable<decimal> taxPayerWHT, Nullable<decimal> previoustaxpaid, Nullable<System.DateTime> previoustaxdate, string paymentMethod, Nullable<decimal> currenttaxamount, Nullable<System.DateTime> currenttaxduedate, Nullable<System.DateTime> nexttaxdate, Nullable<decimal> nexttaxamount, Nullable<int> bankID, string bankBranch, Nullable<System.DateTime> lastModifiedDate, string lastModifiedAuthid, string lastModifiedUid, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIDParameter = itbID.HasValue ?
                new ObjectParameter("ItbID", itbID) :
                new ObjectParameter("ItbID", typeof(int));
    
            var taxIDParameter = taxID != null ?
                new ObjectParameter("TaxID", taxID) :
                new ObjectParameter("TaxID", typeof(string));
    
            var taxPayerWHTParameter = taxPayerWHT.HasValue ?
                new ObjectParameter("TaxPayerWHT", taxPayerWHT) :
                new ObjectParameter("TaxPayerWHT", typeof(decimal));
    
            var previoustaxpaidParameter = previoustaxpaid.HasValue ?
                new ObjectParameter("Previoustaxpaid", previoustaxpaid) :
                new ObjectParameter("Previoustaxpaid", typeof(decimal));
    
            var previoustaxdateParameter = previoustaxdate.HasValue ?
                new ObjectParameter("Previoustaxdate", previoustaxdate) :
                new ObjectParameter("Previoustaxdate", typeof(System.DateTime));
    
            var paymentMethodParameter = paymentMethod != null ?
                new ObjectParameter("PaymentMethod", paymentMethod) :
                new ObjectParameter("PaymentMethod", typeof(string));
    
            var currenttaxamountParameter = currenttaxamount.HasValue ?
                new ObjectParameter("Currenttaxamount", currenttaxamount) :
                new ObjectParameter("Currenttaxamount", typeof(decimal));
    
            var currenttaxduedateParameter = currenttaxduedate.HasValue ?
                new ObjectParameter("Currenttaxduedate", currenttaxduedate) :
                new ObjectParameter("Currenttaxduedate", typeof(System.DateTime));
    
            var nexttaxdateParameter = nexttaxdate.HasValue ?
                new ObjectParameter("Nexttaxdate", nexttaxdate) :
                new ObjectParameter("Nexttaxdate", typeof(System.DateTime));
    
            var nexttaxamountParameter = nexttaxamount.HasValue ?
                new ObjectParameter("Nexttaxamount", nexttaxamount) :
                new ObjectParameter("Nexttaxamount", typeof(decimal));
    
            var bankIDParameter = bankID.HasValue ?
                new ObjectParameter("BankID", bankID) :
                new ObjectParameter("BankID", typeof(int));
    
            var bankBranchParameter = bankBranch != null ?
                new ObjectParameter("BankBranch", bankBranch) :
                new ObjectParameter("BankBranch", typeof(string));
    
            var lastModifiedDateParameter = lastModifiedDate.HasValue ?
                new ObjectParameter("LastModifiedDate", lastModifiedDate) :
                new ObjectParameter("LastModifiedDate", typeof(System.DateTime));
    
            var lastModifiedAuthidParameter = lastModifiedAuthid != null ?
                new ObjectParameter("LastModifiedAuthid", lastModifiedAuthid) :
                new ObjectParameter("LastModifiedAuthid", typeof(string));
    
            var lastModifiedUidParameter = lastModifiedUid != null ?
                new ObjectParameter("LastModifiedUid", lastModifiedUid) :
                new ObjectParameter("LastModifiedUid", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_PaymentHistory", itbIDParameter, taxIDParameter, taxPayerWHTParameter, previoustaxpaidParameter, previoustaxdateParameter, paymentMethodParameter, currenttaxamountParameter, currenttaxduedateParameter, nexttaxdateParameter, nexttaxamountParameter, bankIDParameter, bankBranchParameter, lastModifiedDateParameter, lastModifiedAuthidParameter, lastModifiedUidParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_PersonalData(Nullable<int> itbId, string taxID, string clientFirstname, string clentMidname, string clientLastname, string clientTIN, Nullable<int> clientTaxtype, string tINVerificationStatus, string clientAddress, string clientPhonenumber, string clientEmail, string clientNationalID, Nullable<System.DateTime> clientDOB, string clientOccupation, Nullable<int> companyID, Nullable<int> numberofchildren, string spouseName, string nextofkinName, Nullable<System.DateTime> lastModifiedDate, string lastModifiedAuthid, string lastModifiedUid, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIdParameter = itbId.HasValue ?
                new ObjectParameter("ItbId", itbId) :
                new ObjectParameter("ItbId", typeof(int));
    
            var taxIDParameter = taxID != null ?
                new ObjectParameter("TaxID", taxID) :
                new ObjectParameter("TaxID", typeof(string));
    
            var clientFirstnameParameter = clientFirstname != null ?
                new ObjectParameter("ClientFirstname", clientFirstname) :
                new ObjectParameter("ClientFirstname", typeof(string));
    
            var clentMidnameParameter = clentMidname != null ?
                new ObjectParameter("clentMidname", clentMidname) :
                new ObjectParameter("clentMidname", typeof(string));
    
            var clientLastnameParameter = clientLastname != null ?
                new ObjectParameter("clientLastname", clientLastname) :
                new ObjectParameter("clientLastname", typeof(string));
    
            var clientTINParameter = clientTIN != null ?
                new ObjectParameter("ClientTIN", clientTIN) :
                new ObjectParameter("ClientTIN", typeof(string));
    
            var clientTaxtypeParameter = clientTaxtype.HasValue ?
                new ObjectParameter("ClientTaxtype", clientTaxtype) :
                new ObjectParameter("ClientTaxtype", typeof(int));
    
            var tINVerificationStatusParameter = tINVerificationStatus != null ?
                new ObjectParameter("TINVerificationStatus", tINVerificationStatus) :
                new ObjectParameter("TINVerificationStatus", typeof(string));
    
            var clientAddressParameter = clientAddress != null ?
                new ObjectParameter("ClientAddress", clientAddress) :
                new ObjectParameter("ClientAddress", typeof(string));
    
            var clientPhonenumberParameter = clientPhonenumber != null ?
                new ObjectParameter("ClientPhonenumber", clientPhonenumber) :
                new ObjectParameter("ClientPhonenumber", typeof(string));
    
            var clientEmailParameter = clientEmail != null ?
                new ObjectParameter("ClientEmail", clientEmail) :
                new ObjectParameter("ClientEmail", typeof(string));
    
            var clientNationalIDParameter = clientNationalID != null ?
                new ObjectParameter("ClientNationalID", clientNationalID) :
                new ObjectParameter("ClientNationalID", typeof(string));
    
            var clientDOBParameter = clientDOB.HasValue ?
                new ObjectParameter("ClientDOB", clientDOB) :
                new ObjectParameter("ClientDOB", typeof(System.DateTime));
    
            var clientOccupationParameter = clientOccupation != null ?
                new ObjectParameter("ClientOccupation", clientOccupation) :
                new ObjectParameter("ClientOccupation", typeof(string));
    
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            var numberofchildrenParameter = numberofchildren.HasValue ?
                new ObjectParameter("Numberofchildren", numberofchildren) :
                new ObjectParameter("Numberofchildren", typeof(int));
    
            var spouseNameParameter = spouseName != null ?
                new ObjectParameter("SpouseName", spouseName) :
                new ObjectParameter("SpouseName", typeof(string));
    
            var nextofkinNameParameter = nextofkinName != null ?
                new ObjectParameter("NextofkinName", nextofkinName) :
                new ObjectParameter("NextofkinName", typeof(string));
    
            var lastModifiedDateParameter = lastModifiedDate.HasValue ?
                new ObjectParameter("LastModifiedDate", lastModifiedDate) :
                new ObjectParameter("LastModifiedDate", typeof(System.DateTime));
    
            var lastModifiedAuthidParameter = lastModifiedAuthid != null ?
                new ObjectParameter("LastModifiedAuthid", lastModifiedAuthid) :
                new ObjectParameter("LastModifiedAuthid", typeof(string));
    
            var lastModifiedUidParameter = lastModifiedUid != null ?
                new ObjectParameter("LastModifiedUid", lastModifiedUid) :
                new ObjectParameter("LastModifiedUid", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_PersonalData", itbIdParameter, taxIDParameter, clientFirstnameParameter, clentMidnameParameter, clientLastnameParameter, clientTINParameter, clientTaxtypeParameter, tINVerificationStatusParameter, clientAddressParameter, clientPhonenumberParameter, clientEmailParameter, clientNationalIDParameter, clientDOBParameter, clientOccupationParameter, companyIDParameter, numberofchildrenParameter, spouseNameParameter, nextofkinNameParameter, lastModifiedDateParameter, lastModifiedAuthidParameter, lastModifiedUidParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_TaxReturn(Nullable<int> itbID, string taxID, Nullable<decimal> taxPayerWHT, Nullable<decimal> taxPayerrefund, Nullable<System.DateTime> taxduedate, Nullable<System.DateTime> taxpaiddate, Nullable<int> transactiontype, Nullable<decimal> amountpaid, Nullable<decimal> taxBalance, string taxLevel, Nullable<int> taxtype, string taxPayerNationalID, string taxPayerPhonenumber, string taxPayerAddress, string taxPayerSpousename, string taxPayerSpousenumber, Nullable<decimal> taxreFund, Nullable<System.DateTime> lastModifiedDate, string lastModifiedAuthid, string lastModifiedUid, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIDParameter = itbID.HasValue ?
                new ObjectParameter("ItbID", itbID) :
                new ObjectParameter("ItbID", typeof(int));
    
            var taxIDParameter = taxID != null ?
                new ObjectParameter("TaxID", taxID) :
                new ObjectParameter("TaxID", typeof(string));
    
            var taxPayerWHTParameter = taxPayerWHT.HasValue ?
                new ObjectParameter("TaxPayerWHT", taxPayerWHT) :
                new ObjectParameter("TaxPayerWHT", typeof(decimal));
    
            var taxPayerrefundParameter = taxPayerrefund.HasValue ?
                new ObjectParameter("TaxPayerrefund", taxPayerrefund) :
                new ObjectParameter("TaxPayerrefund", typeof(decimal));
    
            var taxduedateParameter = taxduedate.HasValue ?
                new ObjectParameter("Taxduedate", taxduedate) :
                new ObjectParameter("Taxduedate", typeof(System.DateTime));
    
            var taxpaiddateParameter = taxpaiddate.HasValue ?
                new ObjectParameter("Taxpaiddate", taxpaiddate) :
                new ObjectParameter("Taxpaiddate", typeof(System.DateTime));
    
            var transactiontypeParameter = transactiontype.HasValue ?
                new ObjectParameter("Transactiontype", transactiontype) :
                new ObjectParameter("Transactiontype", typeof(int));
    
            var amountpaidParameter = amountpaid.HasValue ?
                new ObjectParameter("Amountpaid", amountpaid) :
                new ObjectParameter("Amountpaid", typeof(decimal));
    
            var taxBalanceParameter = taxBalance.HasValue ?
                new ObjectParameter("TaxBalance", taxBalance) :
                new ObjectParameter("TaxBalance", typeof(decimal));
    
            var taxLevelParameter = taxLevel != null ?
                new ObjectParameter("TaxLevel", taxLevel) :
                new ObjectParameter("TaxLevel", typeof(string));
    
            var taxtypeParameter = taxtype.HasValue ?
                new ObjectParameter("Taxtype", taxtype) :
                new ObjectParameter("Taxtype", typeof(int));
    
            var taxPayerNationalIDParameter = taxPayerNationalID != null ?
                new ObjectParameter("TaxPayerNationalID", taxPayerNationalID) :
                new ObjectParameter("TaxPayerNationalID", typeof(string));
    
            var taxPayerPhonenumberParameter = taxPayerPhonenumber != null ?
                new ObjectParameter("TaxPayerPhonenumber", taxPayerPhonenumber) :
                new ObjectParameter("TaxPayerPhonenumber", typeof(string));
    
            var taxPayerAddressParameter = taxPayerAddress != null ?
                new ObjectParameter("TaxPayerAddress", taxPayerAddress) :
                new ObjectParameter("TaxPayerAddress", typeof(string));
    
            var taxPayerSpousenameParameter = taxPayerSpousename != null ?
                new ObjectParameter("TaxPayerSpousename", taxPayerSpousename) :
                new ObjectParameter("TaxPayerSpousename", typeof(string));
    
            var taxPayerSpousenumberParameter = taxPayerSpousenumber != null ?
                new ObjectParameter("TaxPayerSpousenumber", taxPayerSpousenumber) :
                new ObjectParameter("TaxPayerSpousenumber", typeof(string));
    
            var taxreFundParameter = taxreFund.HasValue ?
                new ObjectParameter("TaxreFund", taxreFund) :
                new ObjectParameter("TaxreFund", typeof(decimal));
    
            var lastModifiedDateParameter = lastModifiedDate.HasValue ?
                new ObjectParameter("LastModifiedDate", lastModifiedDate) :
                new ObjectParameter("LastModifiedDate", typeof(System.DateTime));
    
            var lastModifiedAuthidParameter = lastModifiedAuthid != null ?
                new ObjectParameter("LastModifiedAuthid", lastModifiedAuthid) :
                new ObjectParameter("LastModifiedAuthid", typeof(string));
    
            var lastModifiedUidParameter = lastModifiedUid != null ?
                new ObjectParameter("LastModifiedUid", lastModifiedUid) :
                new ObjectParameter("LastModifiedUid", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_TaxReturn", itbIDParameter, taxIDParameter, taxPayerWHTParameter, taxPayerrefundParameter, taxduedateParameter, taxpaiddateParameter, transactiontypeParameter, amountpaidParameter, taxBalanceParameter, taxLevelParameter, taxtypeParameter, taxPayerNationalIDParameter, taxPayerPhonenumberParameter, taxPayerAddressParameter, taxPayerSpousenameParameter, taxPayerSpousenumberParameter, taxreFundParameter, lastModifiedDateParameter, lastModifiedAuthidParameter, lastModifiedUidParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_TaxType(Nullable<int> itbID, string taxtypename, Nullable<System.DateTime> lastModifiedDate, string lastModifiedAuthid, string lastModifiedUid, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIDParameter = itbID.HasValue ?
                new ObjectParameter("ItbID", itbID) :
                new ObjectParameter("ItbID", typeof(int));
    
            var taxtypenameParameter = taxtypename != null ?
                new ObjectParameter("Taxtypename", taxtypename) :
                new ObjectParameter("Taxtypename", typeof(string));
    
            var lastModifiedDateParameter = lastModifiedDate.HasValue ?
                new ObjectParameter("LastModifiedDate", lastModifiedDate) :
                new ObjectParameter("LastModifiedDate", typeof(System.DateTime));
    
            var lastModifiedAuthidParameter = lastModifiedAuthid != null ?
                new ObjectParameter("LastModifiedAuthid", lastModifiedAuthid) :
                new ObjectParameter("LastModifiedAuthid", typeof(string));
    
            var lastModifiedUidParameter = lastModifiedUid != null ?
                new ObjectParameter("LastModifiedUid", lastModifiedUid) :
                new ObjectParameter("LastModifiedUid", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_TaxType", itbIDParameter, taxtypenameParameter, lastModifiedDateParameter, lastModifiedAuthidParameter, lastModifiedUidParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_TINverification(Nullable<int> itbID, string tIN, string tINHoldername, string tINHolderaddress, string tINHolderphone, Nullable<System.DateTime> lastModifiedDate, string lastModifiedAuthid, string lastModifiedUid, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIDParameter = itbID.HasValue ?
                new ObjectParameter("ItbID", itbID) :
                new ObjectParameter("ItbID", typeof(int));
    
            var tINParameter = tIN != null ?
                new ObjectParameter("TIN", tIN) :
                new ObjectParameter("TIN", typeof(string));
    
            var tINHoldernameParameter = tINHoldername != null ?
                new ObjectParameter("TINHoldername", tINHoldername) :
                new ObjectParameter("TINHoldername", typeof(string));
    
            var tINHolderaddressParameter = tINHolderaddress != null ?
                new ObjectParameter("TINHolderaddress", tINHolderaddress) :
                new ObjectParameter("TINHolderaddress", typeof(string));
    
            var tINHolderphoneParameter = tINHolderphone != null ?
                new ObjectParameter("TINHolderphone", tINHolderphone) :
                new ObjectParameter("TINHolderphone", typeof(string));
    
            var lastModifiedDateParameter = lastModifiedDate.HasValue ?
                new ObjectParameter("LastModifiedDate", lastModifiedDate) :
                new ObjectParameter("LastModifiedDate", typeof(System.DateTime));
    
            var lastModifiedAuthidParameter = lastModifiedAuthid != null ?
                new ObjectParameter("LastModifiedAuthid", lastModifiedAuthid) :
                new ObjectParameter("LastModifiedAuthid", typeof(string));
    
            var lastModifiedUidParameter = lastModifiedUid != null ?
                new ObjectParameter("LastModifiedUid", lastModifiedUid) :
                new ObjectParameter("LastModifiedUid", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_TINverification", itbIDParameter, tINParameter, tINHoldernameParameter, tINHolderaddressParameter, tINHolderphoneParameter, lastModifiedDateParameter, lastModifiedAuthidParameter, lastModifiedUidParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    
        public virtual int POST_TransactionDetail(Nullable<int> itbID, string transactionType, Nullable<System.DateTime> lastModifiedDate, string lastModifiedAuthid, string lastModifiedUid, string status, string createdBy, Nullable<System.DateTime> createDate, Nullable<int> taskid, ObjectParameter retVal, ObjectParameter retMsg)
        {
            var itbIDParameter = itbID.HasValue ?
                new ObjectParameter("ItbID", itbID) :
                new ObjectParameter("ItbID", typeof(int));
    
            var transactionTypeParameter = transactionType != null ?
                new ObjectParameter("TransactionType", transactionType) :
                new ObjectParameter("TransactionType", typeof(string));
    
            var lastModifiedDateParameter = lastModifiedDate.HasValue ?
                new ObjectParameter("LastModifiedDate", lastModifiedDate) :
                new ObjectParameter("LastModifiedDate", typeof(System.DateTime));
    
            var lastModifiedAuthidParameter = lastModifiedAuthid != null ?
                new ObjectParameter("LastModifiedAuthid", lastModifiedAuthid) :
                new ObjectParameter("LastModifiedAuthid", typeof(string));
    
            var lastModifiedUidParameter = lastModifiedUid != null ?
                new ObjectParameter("LastModifiedUid", lastModifiedUid) :
                new ObjectParameter("LastModifiedUid", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var createDateParameter = createDate.HasValue ?
                new ObjectParameter("CreateDate", createDate) :
                new ObjectParameter("CreateDate", typeof(System.DateTime));
    
            var taskidParameter = taskid.HasValue ?
                new ObjectParameter("taskid", taskid) :
                new ObjectParameter("taskid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_TransactionDetail", itbIDParameter, transactionTypeParameter, lastModifiedDateParameter, lastModifiedAuthidParameter, lastModifiedUidParameter, statusParameter, createdByParameter, createDateParameter, taskidParameter, retVal, retMsg);
        }
    }
}
