//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tax_AK.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxReturn
    {
        public int taskid { get; set; }
        public int ItbID { get; set; }
        public string TaxID { get; set; }
        public Nullable<decimal> TaxPayerWHT { get; set; }
        public Nullable<decimal> TaxPayerrefund { get; set; }
        public Nullable<System.DateTime> Taxduedate { get; set; }
        public Nullable<System.DateTime> Taxpaiddate { get; set; }
        public int Transactiontype { get; set; }
        public Nullable<decimal> Amountpaid { get; set; }
        public Nullable<decimal> TaxBalance { get; set; }
        public string TaxLevel { get; set; }
        public int Taxtype { get; set; }
        public string TaxPayerNationalID { get; set; }
        public string TaxPayerPhonenumber { get; set; }
        public string TaxPayerAddress { get; set; }
        public string TaxPayerSpousename { get; set; }
        public string TaxPayerSpousenumber { get; set; }
        public Nullable<decimal> TaxreFund { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedAuthid { get; set; }
        public string LastModifiedUid { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }

        public virtual TaxType TaxType1 { get; set; }
        public virtual TransactionDetail TransactionDetail { get; set; }
    }
}
